# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Town

# Model Form Field configuration
form: $/planetadeleste/locationtown/models/town/fields.yaml

# Model Class name
modelClass: PlanetaDelEste\LocationTown\Models\Town

# Default redirect location
defaultRedirect: planetadeleste/locationtown/towns

# Create page
create:
  title: planetadeleste.locationtown::lang.form.create_town
  redirect: planetadeleste/locationtown/towns
  redirectClose: planetadeleste/locationtown/towns

# Update page
update:
  title: planetadeleste.locationtown::lang.form.edit_town
  redirect: planetadeleste/locationtown/towns
  redirectClose: planetadeleste/locationtown/towns

# Preview page
preview:
  title: planetadeleste.locationtown::lang.form.preview_town
